external: rkwifibt: add some features
1. add ap6xxx wifi rftest.sh
2. make rk_wifi_init log to syslog
3. add separate S36XXX for different configurations

Signed-off-by: Yao Xiao <xiaoyao@rock-chips.com>
Change-Id: Icbeeadd16f5b14b08bb30dcd2fab199869a7ee64

diff --git a/S36load_ampakall_wifi_modules b/S36load_ampakall_wifi_modules
--- a/S36load_ampakall_wifi_modules
+++ b/S36load_ampakall_wifi_modules
@@ -2,9 +2,6 @@
 
 case "$1" in
 	start)
-
-		echo 1 > /sys/class/rfkill/rfkill1/state
-
 		if [ ! -d "/userdata/" ];then
 			echo "userdata is not mounted!!!"
 			exit 1
@@ -24,6 +21,12 @@ case "$1" in
 			cp /etc/dnsmasq.conf /userdata/bin/
 			sync
 		fi
+
+		printf "load wifi modules: "
+		rk_wifi_init BT_TTY_DEV
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
+
+		wl PM 0
 
 		;;
 	stop)
